site_name: Guruplug
site_author: Antonio Martinez Fernandez
repo_url: https://github.com/AntonioMrtz/guruplug
site_description: Guruplug Documentation
remote_branch: gh-pages

nav:
  - Home: index.md
  - Serial connection: Serial-connection.md
  - Going root: Going-root.md
  - Unbrick bootloader: Unbrick-bootloader.md
  - Network issues: Network-issues.md
  - Update repository sources: Update-repository-sources.md
  - Boot process: Boot-process.md
  - Partition memory layout: Partition-Memory-Layout.md
  - Learnt concepts: Learnt-concepts.md
  - Tethering using USB: Tethering-USB.md
  - Boot from USB: Boot-from-USB.md
  - Wifi and Bluetooth drivers: Wifi-Bt-Drivers.md
  - Power consumption: Power-consumption.md

theme:
  logo: assets/logo.png
  name: material
  favicon: assets/logo.png
  features:
    - navigation.indexes
  palette:
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences